### PR TITLE
this should be litematica not carpet

### PR DESCRIPTION
**Pull request by DragonEggBedrockBreaking**

### CODE REVIEW

**Comment by jensvh** [comment]
Well found, thanks!

**Comment by DragonEggBedrockBreaking** [comment]
Well I originally added the carpet parent to litematica-printer upstream, so I am partly to blame....

**Comment by jensvh** [comment]
No worries. I tried to merge your Pull request and somehow i managed to do it in 2 commits instead of one.

**Comment by DragonEggBedrockBreaking** [comment]
If you merge with a merge commit (equivalent to `git merge`) you get a merge commit. If you rebase-merge, (similar to `git rebase`) you dont get a merge commit but all PR commits are individually there. If you squash-merge (equivalent to `git merge --squash`) all commits in the PR are merged into one commit.

For this PR, since there is only one commit, rebase-merging and squash-merging does the same thing, and would both work if you want to avoid a merge commit.

**Comment by jensvh** [comment]
Ow thanks a lot!

**Pull request merged**
