### PR TITLE
implement accurateBlockPlacement code

### PR DESCRIPTION
**Pull request by aria1th**
tested in creative, seems to work good
should change player-side to arbitary side if available, it uses player facing direction at default

### CODE REVIEW

**Comment by aria1th** [comment]
Wait until I fix masa's original bug pls

**Comment by aria1th** [comment]
Fixed now

**Comment by jensvh** [comment]
Sounds great, but could you give me a quick explanation of what is does? And what the CarpetProtocol is?
I gave it a go with the release on your fork, but it seems the rotation of comparators/repeaters and stairs isn't working as expected.

**Comment by aria1th** [comment]
I fixed that recently : carpet protocol uses invaild X to code its state. but due to original masa's code error, it was miscoded and easyplace itself used to be faulty : comparator / repeater was rotated when it has different delay.
https://github.com/gnembon/carpet-extra/blob/master/src/main/java/carpetextra/utils/BlockPlacer.java

I found that it was using 16 instead of 32, and fixed it.(also delay too), so now it places block with state, don't have to click more times.
 maybe I released wrong one?

**Comment by jensvh** [comment]
If you can confirm that it works, its fine for me and I'll merge it.

**Comment by aria1th** [comment]
https://user-images.githubusercontent.com/35677394/129720357-00cc1aa4-90b1-4afd-bd57-9b6b36f1d6e5.mp4

Here is a video that how it works
it needs 'accurateblockplacement' in carpet extra / quickcarpet to work properly, so default is set to off

**Comment by aria1th** [comment]
but I  guess it might not work properly with hoppers, so maybe should be fixed once more...

**Comment by jensvh** [comment]
For some reason I can only hear audio, but its good enough.

**Pull request merged**
